"""
KubePanel Kubernetes Integration

This module provides Django integration with the KubePanel Kubernetes operator.
"""

from .client import (
    K8sClientError,
    K8sConnectionError,
    K8sNotFoundError,
    K8sConflictError,
    K8sValidationError,
)

from .domain import (
    DomainSpec,
    DomainStatus,
    Domain,
    create_domain,
    get_domain,
    get_domain_by_cr_name,
    get_domain_config,
    get_dns_status,
    add_dns_record,
    update_dns_record,
    delete_dns_record_from_cr,
    list_domains,
    update_domain,
    patch_domain,
    delete_domain,
    suspend_domain,
    unsuspend_domain,
    domain_exists,
)

from .secrets import (
    get_secret_value,
    get_secret_from_ref,
    get_sftp_password,
    get_database_password,
    update_sftp_password,
    update_database_password,
    create_dkim_secret,
)

from .backup import (
    Backup,
    BackupStatus,
    list_backups,
    get_backup,
    create_backup,
    delete_backup,
)

from .restore import (
    Restore,
    RestoreStatus,
    list_restores,
    get_restore,
    create_restore,
    delete_restore,
)

from .dnszone import (
    DNSZone,
    DNSZoneStatus,
    create_dnszone,
    get_dnszone,
    dnszone_exists,
    delete_dnszone,
    patch_dnszone_records,
    add_dns_record as add_dnszone_record,
    update_dns_record as update_dnszone_record,
    delete_dns_record as delete_dnszone_record,
    get_dns_records as get_dnszone_records,
    get_dns_record as get_dnszone_record,
    get_dns_status as get_dnszone_status,
)

from .global_waf import (
    GlobalWAF,
    GlobalWAFStatus,
    get_globalwaf,
    globalwaf_exists,
    create_globalwaf,
    delete_globalwaf,
    patch_globalwaf,
    set_globalwaf_enabled,
    get_or_create_globalwaf,
    add_waf_rule,
    update_waf_rule,
    delete_waf_rule,
    get_waf_rule,
    get_waf_rules,
)

from .l3_firewall import (
    GlobalL3Firewall,
    L3FirewallStatus,
    get_l3_firewall,
    l3_firewall_exists,
    create_l3_firewall,
    delete_l3_firewall,
    patch_l3_firewall,
    set_l3_firewall_enabled,
    get_or_create_l3_firewall,
    add_l3_rule,
    update_l3_rule,
    delete_l3_rule,
    get_l3_rule,
    get_l3_rules,
)

from .domain_waf import (
    DomainWAF,
    DomainWAFStatus,
    get_domainwaf,
    domainwaf_exists,
    create_domainwaf,
    delete_domainwaf,
    patch_domainwaf,
    set_domainwaf_enabled,
    get_or_create_domainwaf,
    add_domain_waf_rule,
    update_domain_waf_rule,
    delete_domain_waf_rule,
    get_domain_waf_rule,
    get_domain_waf_rules,
    set_geo_blocking_enabled,
    add_blocked_country,
    remove_blocked_country,
    get_domain_protected_paths,
    get_domain_protected_path,
    add_domain_protected_path,
    update_domain_protected_path,
    delete_domain_protected_path,
)

from .smtp_firewall import (
    SMTPFirewall,
    SMTPFirewallStatus,
    RateLimit,
    get_smtp_firewall,
    smtp_firewall_exists,
    create_smtp_firewall,
    delete_smtp_firewall,
    patch_smtp_firewall,
    get_or_create_smtp_firewall,
    add_blocked_sender,
    remove_blocked_sender,
    add_blocked_domain,
    remove_blocked_domain,
    add_blocked_ip,
    remove_blocked_ip,
    add_rate_limit,
    remove_rate_limit,
    get_rate_limit,
    get_all_rate_limits,
)

__all__ = [
    # Exceptions
    'K8sClientError',
    'K8sConnectionError',
    'K8sNotFoundError',
    'K8sConflictError',
    'K8sValidationError',
    
    # Domain classes
    'DomainSpec',
    'DomainStatus',
    'Domain',
    
    # Domain operations
    'create_domain',
    'get_domain',
    'get_domain_by_cr_name',
    'get_domain_config',
    'get_dns_status',
    'add_dns_record',
    'update_dns_record',
    'delete_dns_record_from_cr',
    'list_domains',
    'update_domain',
    'patch_domain',
    'delete_domain',
    'suspend_domain',
    'unsuspend_domain',
    'domain_exists',
    
    # Secret operations
    'get_secret_value',
    'get_secret_from_ref',
    'get_sftp_password',
    'get_database_password',
    'update_sftp_password',
    'update_database_password',
    'create_dkim_secret',

    # Backup operations
    'Backup',
    'BackupStatus',
    'list_backups',
    'get_backup',
    'create_backup',
    'delete_backup',

    # Restore operations
    'Restore',
    'RestoreStatus',
    'list_restores',
    'get_restore',
    'create_restore',
    'delete_restore',

    # DNSZone operations
    'DNSZone',
    'DNSZoneStatus',
    'create_dnszone',
    'get_dnszone',
    'dnszone_exists',
    'delete_dnszone',
    'patch_dnszone_records',
    'add_dnszone_record',
    'update_dnszone_record',
    'delete_dnszone_record',
    'get_dnszone_records',
    'get_dnszone_record',
    'get_dnszone_status',

    # GlobalWAF operations
    'GlobalWAF',
    'GlobalWAFStatus',
    'get_globalwaf',
    'globalwaf_exists',
    'create_globalwaf',
    'delete_globalwaf',
    'patch_globalwaf',
    'set_globalwaf_enabled',
    'get_or_create_globalwaf',
    'add_waf_rule',
    'update_waf_rule',
    'delete_waf_rule',
    'get_waf_rule',
    'get_waf_rules',

    # GlobalL3Firewall operations
    'GlobalL3Firewall',
    'L3FirewallStatus',
    'get_l3_firewall',
    'l3_firewall_exists',
    'create_l3_firewall',
    'delete_l3_firewall',
    'patch_l3_firewall',
    'set_l3_firewall_enabled',
    'get_or_create_l3_firewall',
    'add_l3_rule',
    'update_l3_rule',
    'delete_l3_rule',
    'get_l3_rule',
    'get_l3_rules',

    # DomainWAF operations
    'DomainWAF',
    'DomainWAFStatus',
    'get_domainwaf',
    'domainwaf_exists',
    'create_domainwaf',
    'delete_domainwaf',
    'patch_domainwaf',
    'set_domainwaf_enabled',
    'get_or_create_domainwaf',
    'add_domain_waf_rule',
    'update_domain_waf_rule',
    'delete_domain_waf_rule',
    'get_domain_waf_rule',
    'get_domain_waf_rules',
    'set_geo_blocking_enabled',
    'add_blocked_country',
    'remove_blocked_country',
    'get_domain_protected_paths',
    'get_domain_protected_path',
    'add_domain_protected_path',
    'update_domain_protected_path',
    'delete_domain_protected_path',

    # SMTPFirewall operations
    'SMTPFirewall',
    'SMTPFirewallStatus',
    'RateLimit',
    'get_smtp_firewall',
    'smtp_firewall_exists',
    'create_smtp_firewall',
    'delete_smtp_firewall',
    'patch_smtp_firewall',
    'get_or_create_smtp_firewall',
    'add_blocked_sender',
    'remove_blocked_sender',
    'add_blocked_domain',
    'remove_blocked_domain',
    'add_blocked_ip',
    'remove_blocked_ip',
    'add_rate_limit',
    'remove_rate_limit',
    'get_rate_limit',
    'get_all_rate_limits',
]
