"""
Kubernetes Secrets Operations

Read secrets from Kubernetes (generated by the operator).
Django never creates secrets - the operator does.
"""

from kubernetes.client.rest import ApiException
import base64
import logging
from typing import Optional

from .client import get_core_api, handle_api_exception

logger = logging.getLogger(__name__)


def get_secret_value(
    name: str,
    namespace: str,
    key: str
) -> Optional[str]:
    """
    Get a secret value from Kubernetes.
    
    Args:
        name: Secret name
        namespace: Secret namespace
        key: Key within the secret data
    
    Returns:
        Decoded secret value, or None if not found
    
    Raises:
        K8sNotFoundError: If secret not found
        K8sClientError: For other K8s errors
    """
    core_api = get_core_api()
    
    try:
        secret = core_api.read_namespaced_secret(name=name, namespace=namespace)
        
        if secret.data and key in secret.data:
            # Secret data is base64 encoded
            return base64.b64decode(secret.data[key]).decode('utf-8')
        
        logger.warning(f"Key '{key}' not found in secret '{namespace}/{name}'")
        return None
        
    except ApiException as e:
        handle_api_exception(e, f"Secret '{namespace}/{name}'")


def get_secret_from_ref(secret_ref: dict) -> Optional[str]:
    """
    Get a secret value using a secretRef dict.
    
    Args:
        secret_ref: Dict with 'name', 'namespace', and 'key'
    
    Returns:
        Decoded secret value, or None if ref is invalid
    """
    if not secret_ref:
        return None
    
    name = secret_ref.get('name')
    namespace = secret_ref.get('namespace')
    key = secret_ref.get('key')
    
    if not all([name, namespace, key]):
        logger.warning(f"Invalid secret ref: {secret_ref}")
        return None
    
    return get_secret_value(name, namespace, key)


def get_sftp_password(domain_status) -> Optional[str]:
    """
    Get SFTP password for a domain from its status.
    
    Args:
        domain_status: DomainStatus object
    
    Returns:
        SFTP password or None
    """
    secret_ref = domain_status.sftp_password_secret_ref
    return get_secret_from_ref(secret_ref)


def get_database_password(domain_status) -> Optional[str]:
    """
    Get database password for a domain from its status.
    
    Args:
        domain_status: DomainStatus object
    
    Returns:
        Database password or None
    """
    secret_ref = domain_status.database_password_secret_ref
    return get_secret_from_ref(secret_ref)
